/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_MyInterface */

#ifndef _Included_com_example_jni_MyInterface
#define _Included_com_example_jni_MyInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_MyInterface
 * Method:    stringTestNdk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jni_MyInterface_stringTestNdk
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jni_MyInterface
 * Method:    stringTestNdk2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jni_MyInterface_stringTestNdk2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
